apiVersion: v1
kind: Service
metadata:
  name: user_management
  labels:
    app: user_management
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9084
      targetPort: 9084
  selector:
    app: user_management
